# Generated by Django 3.1.6 on 2021-04-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0003_university_super_admin'),
        ('RSO', '0002_rso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='University', to='Universities.university'),
        ),
    ]
