# Generated by Django 3.1.6 on 2021-03-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0004_remove_university_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RSO', '0003_auto_20210313_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='University', to='Universities.university'),
        ),
        migrations.AlterField(
            model_name='rso',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
