# Generated by Django 3.1.6 on 2021-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSO', '0004_auto_20210314_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
