# Generated by Django 3.1.6 on 2021-03-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSO', '0005_rso_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rso',
            name='total_students',
            field=models.IntegerField(null=True),
        ),
    ]
