# Generated by Django 3.1.6 on 2021-02-27 01:26

import Universities.models
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=254)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('picture', models.ImageField(upload_to=Universities.models.university_directory_path)),
                ('number_of_students', models.IntegerField()),
            ],
        ),
    ]
