# Generated by Django 3.1.6 on 2021-03-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='name',
            new_name='location_name',
        ),
    ]
