# Generated by Django 3.1.6 on 2021-03-11 16:15

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [28.6014075, -81.20134150000001], 'marker_color': 'red'}),
        ),
    ]
