# Generated by Django 3.1.6 on 2021-03-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0002_auto_20210311_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='abbreviation',
        ),
    ]
