# Generated by Django 3.1.6 on 2021-03-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0003_remove_university_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='email',
        ),
    ]
