# Generated by Django 3.1.6 on 2021-03-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0004_remove_university_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=14, null=True),
        ),
    ]
