# Generated by Django 3.1.6 on 2021-03-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0005_auto_20210314_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email_domain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
