# Generated by Django 3.1.6 on 2021-03-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0006_university_email_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
