# Generated by Django 3.1.6 on 2021-03-17 00:09

import Universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0008_remove_university_email_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=Universities.models.university_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='university',
            name='picture',
        ),
        migrations.AddField(
            model_name='university',
            name='pictures',
            field=models.ManyToManyField(to='Universities.Photos'),
        ),
    ]
