# Generated by Django 3.1.6 on 2021-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0009_auto_20210316_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
