# Generated by Django 3.1.6 on 2021-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0010_auto_20210317_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
