# Generated by Django 3.1.6 on 2021-03-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0011_auto_20210321_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='university_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
