# Generated by Django 3.1.6 on 2021-04-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210404_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsoNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rso', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rsos',
            field=models.ManyToManyField(to='Users.RsoNumber'),
        ),
    ]
