# Generated by Django 3.1.6 on 2021-02-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20210226_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:26:04'),
        ),
    ]
