# Generated by Django 3.1.6 on 2021-03-03 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0006_auto_20210228_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:28:22'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
