# Generated by Django 3.1.6 on 2021-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20210302_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='15:38:50'),
        ),
    ]
