# Generated by Django 3.1.6 on 2021-03-11 16:00

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_auto_20210309_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='11:00:57'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [28.6014075, -81.20134150000001], 'marker_color': 'red'}),
        ),
    ]
