# Generated by Django 3.1.6 on 2021-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_auto_20210401_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='11:50:41'),
        ),
    ]
