# Generated by Django 3.1.6 on 2021-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20210404_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='12:01:28'),
        ),
    ]
