# Generated by Django 3.1.6 on 2021-03-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20210312_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='15:28:03'),
        ),
    ]
