# Generated by Django 3.1.6 on 2021-04-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_auto_20210410_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:44:56'),
        ),
    ]
