# Generated by Django 3.1.6 on 2021-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0016_auto_20210313_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='12:12:03'),
        ),
    ]
