# Generated by Django 3.1.6 on 2021-04-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0016_auto_20210410_2044'),
        ('Events', '0016_auto_20210410_1310'),
    ]

    operations = [
    ]
