# Generated by Django 3.1.6 on 2021-04-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0018_auto_20210413_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='19:53:57'),
        ),
    ]
