# Generated by Django 3.1.6 on 2021-03-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0018_auto_20210314_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='16:49:10'),
        ),
    ]
