# Generated by Django 3.1.6 on 2021-04-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0019_auto_20210413_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='18:15:08'),
        ),
    ]
