# Generated by Django 3.1.6 on 2021-03-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0020_auto_20210314_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='19:44:21'),
        ),
    ]
