# Generated by Django 3.1.6 on 2021-03-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0021_auto_20210314_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:02:08'),
        ),
    ]
