# Generated by Django 3.1.6 on 2021-03-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0022_auto_20210314_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:19:05'),
        ),
    ]
