# Generated by Django 3.1.6 on 2021-04-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0024_auto_20210415_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(blank=True, default='18:31:26'),
        ),
    ]
