# Generated by Django 3.1.6 on 2021-03-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0026_auto_20210314_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:04:25'),
        ),
    ]
