# Generated by Django 3.1.6 on 2021-03-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0027_auto_20210316_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:09:50'),
        ),
    ]
