# Generated by Django 3.1.6 on 2021-03-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0028_auto_20210316_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='20:10:10'),
        ),
    ]
