# Generated by Django 3.1.6 on 2021-04-16 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0028_auto_20210415_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 21, 18, 5, 679272), null=True),
        ),
    ]
