# Generated by Django 3.1.6 on 2021-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0029_auto_20210316_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='10:02:42'),
        ),
    ]
