# Generated by Django 3.1.6 on 2021-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0030_auto_20210317_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='18:59:47'),
        ),
    ]
