# Generated by Django 3.1.6 on 2021-03-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0031_auto_20210321_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(default='19:04:43'),
        ),
    ]
